export const ACTION_GET_POSTS = "ACTION_GET_POSTS";

export const GET_POSTS_AJAX_CALL_START = 'GET_POSTS_AJAX_CALL_START';
export const GET_POSTS_AJAX_CALL_SUCCESS = 'GET_POSTS_AJAX_CALL_SUCCESS';
export const GET_POSTS_AJAX_CALL_FAILURE = 'GET_POSTS_AJAX_CALL_FAILURE';